### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by Coder-DG** [futo-org/grayjay-plugin-patreon#1]
I'm trying ti find a creator's name that I followed through the regular search. After selecting the Patreon source from the filters nothing shows up.
It worked a couple of months ago but was unabke to load the channel, now it simply doesn't work.
Grayjay 278, plugin 17

**Comment by kaidelorenzo** [comment]
I'm pretty sure Patreon hasn't had normal (home page) search support (because you can't search Patreon globally for content). You can search for creators on the creators tab in Grayjay. I imagine that's what you're remembering being able to do. As far as I'm aware that still works.

There are changes we'll probably make to search in the future that I would imagine would have prevented your issue

- We'll probably make searching combined that way wherever you search you'll have easy access to all kinds of search
- Additionally we'll probably make it so that if a plugin doesn't support a search function it won't show up looking like it might work and then return zero results.

**Comment by Coder-DG** [comment]
You're right, it was through the Creator Search. But even then nothing happens after hitting Subscribe.

Can create a separate issue for that.

**Comment by kaidelorenzo** [comment]
Yeah create another issue. The creator should show up in your subscriptions and creators tabs
